version: "3"

services:
  app:
    restart: always
    build: .
    links:
      - "db:${DB_HOST}"
    volumes:
      - "./migrations/versions:/app/migrations/versions"
    ports:
      - "80:8080"
    env_file:
      - .env

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PSWD}"
      POSTGRES_DATABASE: "${DB_NAME}"
