version: "3"

services:
  app:
    restart: always
    build: .
    volumes:
      - "./migrations/versions:/app/migrations/versions"
    links:
      - "db:${DB_HOST}"
    ports:
      - "8080:8080"