"""empty message

Revision ID: e05d3404e1f7
Revises: ae77424b0fb8
Create Date: 2023-04-16 11:49:33.780356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05d3404e1f7'
down_revision = 'ae77424b0fb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
